"""FitAdapt's framework-independent fitness-intelligence core."""

from fitadapt.adaptive.tdee import AdaptiveTdeeConfig, estimate_adaptive_tdee
from fitadapt.analysis.trends import TrendAnalysisConfig, analyze_observation_trends
from fitadapt.api.app import create_app
from fitadapt.baseline.energy import (
    ACTIVITY_MULTIPLIERS,
    ACTIVITY_POLICY_VERSION,
    REE_FORMULA_VERSION,
    BaselineEnergyEstimate,
    calculate_baseline_energy,
    calculate_mifflin_st_jeor_ree,
)
from fitadapt.baseline.targets import (
    ENERGY_EQUIVALENT_POLICY_VERSION,
    MACRO_POLICY_VERSION,
    CalorieTargetEstimate,
    MacroPolicyInfeasibleError,
    calculate_calorie_target,
    calculate_daily_calorie_adjustment,
)
from fitadapt.domain.observation import DailyObservation, ObservationValidationError
from fitadapt.domain.profile import (
    ActivityLevel,
    Goal,
    ProfileValidationError,
    SexForMifflinEquation,
    UserProfile,
)
from fitadapt.evaluation.tdee import (
    TDEE_BENCHMARK_SCENARIOS,
    TDEE_EVALUATION_POLICY_VERSION,
    TdeeBenchmarkScenario,
    TdeeBenchmarkScenarioResult,
    TdeeBenchmarkSuiteResult,
    TdeeErrorMetrics,
    TdeeEvaluationError,
    TdeeEvaluationResult,
    calculate_tdee_error_metrics,
    evaluate_tdee_estimators,
    run_tdee_benchmark_suite,
)
from fitadapt.ml.interpretation import (
    WeightChangeInterpretationConfig,
    WeightChangeInterpretationResult,
    run_weight_change_interpretation,
)
from fitadapt.ml.weight_change import (
    WeightChangeMlConfig,
    build_synthetic_weight_change_dataset,
    run_weight_change_benchmark,
)
from fitadapt.personalization.lifecycle import (
    PERSONALIZATION_LIFECYCLE_POLICY_VERSION,
    PersonalizationLifecycleConfig,
    PersonalizationLifecycleError,
    PersonalizationLifecycleResult,
    PersonalizationRequirement,
    PersonalizationStage,
    assess_personalization_lifecycle,
)
from fitadapt.personalization.macros import (
    MACRO_PLAN_POLICY_VERSION,
    MacroCalorieSource,
    MacroPlanInfeasibleError,
    MacroStrategy,
    NutritionPreferences,
    NutritionPreferencesError,
    PersonalizedMacroPlan,
    calculate_personalized_macro_plan,
)
from fitadapt.personalization.planning import (
    PERSONALIZED_PLANNING_POLICY_VERSION,
    PersonalizedPlanningError,
    PersonalizedPlanProgression,
    PersonalizedPlanSnapshot,
    PlanCalorieBasis,
    build_personalized_plan_progression,
    build_personalized_plan_snapshot,
)
from fitadapt.recommendation.calories import recommend_calorie_adjustment
from fitadapt.synthetic.history import (
    SyntheticConfigurationError,
    SyntheticHistory,
    SyntheticHistoryConfig,
    generate_synthetic_history,
)

__all__ = [
    "ACTIVITY_MULTIPLIERS",
    "ACTIVITY_POLICY_VERSION",
    "REE_FORMULA_VERSION",
    "ActivityLevel",
    "AdaptiveTdeeConfig",
    "BaselineEnergyEstimate",
    "CalorieTargetEstimate",
    "DailyObservation",
    "ENERGY_EQUIVALENT_POLICY_VERSION",
    "Goal",
    "MACRO_POLICY_VERSION",
    "MACRO_PLAN_POLICY_VERSION",
    "PERSONALIZATION_LIFECYCLE_POLICY_VERSION",
    "PERSONALIZED_PLANNING_POLICY_VERSION",
    "MacroCalorieSource",
    "MacroPlanInfeasibleError",
    "MacroPolicyInfeasibleError",
    "MacroStrategy",
    "NutritionPreferences",
    "NutritionPreferencesError",
    "ObservationValidationError",
    "ProfileValidationError",
    "PersonalizedMacroPlan",
    "PersonalizedPlanProgression",
    "PersonalizedPlanSnapshot",
    "PersonalizedPlanningError",
    "PersonalizationLifecycleConfig",
    "PersonalizationLifecycleError",
    "PersonalizationLifecycleResult",
    "PersonalizationRequirement",
    "PersonalizationStage",
    "PlanCalorieBasis",
    "SexForMifflinEquation",
    "SyntheticConfigurationError",
    "SyntheticHistory",
    "SyntheticHistoryConfig",
    "TDEE_BENCHMARK_SCENARIOS",
    "TDEE_EVALUATION_POLICY_VERSION",
    "TdeeBenchmarkScenario",
    "TdeeBenchmarkScenarioResult",
    "TdeeBenchmarkSuiteResult",
    "TdeeErrorMetrics",
    "TdeeEvaluationError",
    "TdeeEvaluationResult",
    "TrendAnalysisConfig",
    "UserProfile",
    "WeightChangeMlConfig",
    "WeightChangeInterpretationConfig",
    "WeightChangeInterpretationResult",
    "calculate_baseline_energy",
    "calculate_calorie_target",
    "calculate_daily_calorie_adjustment",
    "calculate_mifflin_st_jeor_ree",
    "calculate_personalized_macro_plan",
    "build_personalized_plan_progression",
    "build_personalized_plan_snapshot",
    "assess_personalization_lifecycle",
    "calculate_tdee_error_metrics",
    "create_app",
    "build_synthetic_weight_change_dataset",
    "evaluate_tdee_estimators",
    "generate_synthetic_history",
    "run_tdee_benchmark_suite",
    "run_weight_change_benchmark",
    "run_weight_change_interpretation",
    "recommend_calorie_adjustment",
    "analyze_observation_trends",
    "estimate_adaptive_tdee",
]
